// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkUyiL-UzTAuCttFDaUZRg1ja1PTeyWDE',
    appId: '1:942774878274:web:700f767e12bbd972976ddb',
    messagingSenderId: '942774878274',
    projectId: 'waterdemo-164b9',
    authDomain: 'waterdemo-164b9.firebaseapp.com',
    storageBucket: 'waterdemo-164b9.appspot.com',
    measurementId: 'G-8YSXVLGCK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVaw4ms7JlPjuVOs-2eaQRBa-cZwPVW3s',
    appId: '1:942774878274:android:27ecf7ede14df5d8976ddb',
    messagingSenderId: '942774878274',
    projectId: 'waterdemo-164b9',
    storageBucket: 'waterdemo-164b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpeN4sNrvbz_J8myUVI_TQMyVnGh23yWU',
    appId: '1:942774878274:ios:dddbbc4687e33c32976ddb',
    messagingSenderId: '942774878274',
    projectId: 'waterdemo-164b9',
    storageBucket: 'waterdemo-164b9.appspot.com',
    iosBundleId: 'com.example.waterFilter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpeN4sNrvbz_J8myUVI_TQMyVnGh23yWU',
    appId: '1:942774878274:ios:dddbbc4687e33c32976ddb',
    messagingSenderId: '942774878274',
    projectId: 'waterdemo-164b9',
    storageBucket: 'waterdemo-164b9.appspot.com',
    iosBundleId: 'com.example.waterFilter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkUyiL-UzTAuCttFDaUZRg1ja1PTeyWDE',
    appId: '1:942774878274:web:c3cce5f44227c780976ddb',
    messagingSenderId: '942774878274',
    projectId: 'waterdemo-164b9',
    authDomain: 'waterdemo-164b9.firebaseapp.com',
    storageBucket: 'waterdemo-164b9.appspot.com',
    measurementId: 'G-RJS5WXVWN7',
  );
}
